### PR TITLE
Update ESP32Encoder.cpp

### PR DESCRIPTION
**Pull request by brianmichalk1**

### CODE REVIEW

**Comment by madhephaestus** [comment]
This looks great, have you checked that it compiles on the legacy esp32?

**Comment by brianmichalk1** [comment]
Sorry, I have not.  I've also made another patch for the S3.  I'm not sure how to edit a PR, or if I should create a new one.

**Comment by madhephaestus** [comment]
You can just push that code into patch-1 branch in your repo to add that code to the PR

**Comment by brianmichalk1** [comment]
ok.  This could be tonight.

**Comment by madhephaestus** [comment]
other pull requests that have been merged caused a conflict, can you make your PR merge now so i can merge it?

**Comment by madhephaestus** [comment]
Needs to be mergable

**Pull request closed without merging**
