### PR TITLE
fix compiling with ESP-IDF 5.x,

### PR DESCRIPTION
**Pull request by tueddy**
see https://github.com/madhephaestus/ESP32Encoder/issues/101

### CODE REVIEW

**Comment by madhephaestus** [comment]
can you add the compiler gaurds so this is only added these imports on the older cores? Or have you tested this works in 1.04 and 2.x.x before we merge this?

**Comment by tueddy** [comment]
I've tested with Arduino 2.0.14 & 3.0 but not with Arduino 1.
For safety i've added a compiler define..

**Comment by tueddy** [comment]
An alternative condition would be

`#if ( defined(ESP_ARDUINO_VERSION_MAJOR) && (ESP_ARDUINO_VERSION_MAJOR >= 3) )`

**Comment by madhephaestus** [comment]
I would prefer the  `#if ( defined(ESP_ARDUINO_VERSION_MAJOR) && (ESP_ARDUINO_VERSION_MAJOR >= 3) )` to be backwards compatible and future looking as the major number is increased over time.

**Comment by tueddy** [comment]
Sorry for the inconvenience: With changed directive it does not compile with Arduino 3 / ESP-IDF 5. 

We need additionally
`#include <Arduino.h>`

or change the compiler condition to
`#if ESP_IDF_VERSION_MAJOR >= 5`

@madhephaestus What solution do you prefer?

**Pull request merged**
